project:
  type: website
  

website:
  title: "output_share"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mca.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



