project:
  type: website
  output-dir: docs
  

website:
  title: "Use-it-up tape intervention preliminary results"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - annotated_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



