---
title: "Tape Intervention R Script"
author: "Cas Huisman"
format: html
params:
  path: "C:/Users/huism080/OneDrive - Wageningen University & Research/Research/Study 2/tapeStudy/data/" #specify the folder where the anonymised data is located
---
```{r}
#| echo: false
#| include: false
#| label: libraries

library(table1)
library(vtable)
```

```{r}
#| label: read data
#| echo: false

t0 <- read.csv(url("https://raw.githubusercontent.com/CasHsmn/R_tape/main/data/t0_anon.csv"))
t1 <- read.csv(url("https://raw.githubusercontent.com/CasHsmn/R_tape/main/data/t1_anon.csv"))
t2 <- read.csv(url("https://raw.githubusercontent.com/CasHsmn/R_tape/main/data/t2_anon.csv"))
tall <- read.csv(url("https://raw.githubusercontent.com/CasHsmn/R_tape/main/data/tall_anon.csv"))

```

# Sample Characteristics
```{r}
#| label: sample characteristics
#| echo: false

# Sample descriptives; Label sample variables and create table 1
t0$gender_t0[t0$gender_t0 == 4] <- 3
t0$gender_t0 <- factor(t0$gender_t0, levels = c(1,2,3), labels = c("Female", "Male", "Other"))
t0$condition_t0 <- factor(t0$condition_t0, levels = c("intervention", "control"), labels = c("intervention", "control"))
label(t0$gender_t0) <- "Gender"
label(t0$age_t0) <- "Age"
label(t0$hh_size_t0) <- "Household size"
label(t0$fw_g_t0) <- "Baseline waste"
table1(~ gender_t0 + age_t0 + hh_size_t0 + fw_g_t0 | condition_t0, data = t0)
```

# Descriptives
```{r}
#| label: descriptives
#| echo: false
#| warning: false

st(t0, vars = c("pastweek_1_t0", "pastweek_2_t0", "pastweek_3_t0", "stock_freq_1_t0", "hs_stock_t0", "meal_freq._1_t0", "hs_meal_t0", "snack_freq_1_t0", "hs_snack_t0", "share_freq_1_t0", "hs_share_t0"), labels = c("Days at home", "Days ate at home", "Days prepared food", "Check if near expiry", "Habit: Check if near expired", "Use near expired food in meal", "Habit: Use near expired food in meal", "Snack near expired", "Habit: Snack near expired", "Share near expired", "Habit: Share near expired"), summ = c("mean(x)", "sd(x)", "median(x)"), out = 'kable', title = "Variable descriptives at T0", col.align = "center")

st(t1, vars = c("pastweek_1_t1", "pastweek_2_t1", "pastweek_3_t1", "stock_freq_1_t1", "hs_stock_t1", "meal_freq._1_t1", "hs_meal_t1", "snack_freq_1_t1", "hs_snack_t1", "share_freq_1_t1", "hs_share_t1"), labels = c("Days at home", "Days ate at home", "Days prepared food", "Check if near expiry", "Habit: Check if near expired", "Use near expired food in meal", "Habit: Use near expired food in meal", "Snack near expired", "Habit: Snack near expired", "Share near expired", "Habit: Share near expired"), summ = c("mean(x)", "sd(x)", "median(x)"), out = 'kable', title = "Variable descriptives at T1", col.align = "center")

st(t2, vars = c("pastweek_1_t2", "pastweek_2_t2", "pastweek_3_t2", "stock_freq_1_t2", "hs_stock_t2", "meal_freq._1_t2", "hs_meal_t2", "snack_freq_1_t2", "hs_snack_t2", "share_freq_1_t2", "hs_share_t2"), labels = c("Days at home", "Days ate at home", "Days prepared food", "Check if near expiry", "Habit: Check if near expired", "Use near expired food in meal", "Habit: Use near expired food in meal", "Snack near expired", "Habit: Snack near expired", "Share near expired", "Habit: Share near expired"), summ = c("mean(x)", "sd(x)", "median(x)"), out = 'kable', title = "Variable descriptives at T2", col.align = "center")
```


